# .github/workflows/build-documentation.yml

name: Build-Packages

on:
  # Run on push to main branch
  push:
    branches:
      - main

  # Dispatch if triggered using Github (website)
  workflow_dispatch:

jobs:
  Build-Packages:
    runs-on: macos-latest
    steps:
      - name: Build Swift Packages
        uses: 0xWDG/build-swift@main
