name: Update Contributors List
on:
  # Run on push to main branch
  push:
  # Dispatch if triggered using Github (website)
  workflow_dispatch:

jobs:
  swiftlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: SwiftLint
        run: swiftlint --strict --reporter github-actions-logging

  test_linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Swift test
        run: swift test

  test_macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Swift test
        run: swift test
